name: n8n
services:
  n8n:
    cpu_shares: 90
    command: []
    container_name: n8n
    deploy:
      resources:
        limits:
          memory: 3919M
        reservations:
          memory: "335544320"
    environment:
      - N8N_SECURE_COOKIE=false
      - TZ=Atlantic/Reykjavik
      - WEBHOOK_URL=https://your-site/
    hostname: n8n
    image: n8nio/n8n:1.72.1
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/N8n/icon.png
    ports:
      - target: 5678
        published: "5678"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/n8n
        target: /home/node/.n8n
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
            zh_cn: 时区
      ports:
        - container: "5678"
          description:
            en_us: web port
            zh_cn: web 端口
      volumes:
        - container: /home/node/.n8n
          description:
            en_us: n8n directory.
            zh_cn: n8n 目录。
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: YoussofKhawaja
  category: Utilities
  description:
    en_us: Free and source-available fair-code licensed workflow automation tool.
      Easily automate tasks across different services.
    ru_ru: Бесплатный и с открытым исходным кодом инструмент автоматизации рабочего
      процесса с лицензией fair-code. Легко автоматизируйте задачи через
      различные сервисы.
  developer: n8n
  hostname: n8n.dit-system.ru
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/N8n/icon.png
  index: /
  is_uncontrolled: true
  main: n8n
  port_map: ""
  scheme: https
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/N8n/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/N8n/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/N8n/screenshot-3.png
  store_app_id: n8n
  tagline:
    en_us: Workflow automation tool
    ru_ru: Инструмент автоматизации рабочего процесса
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/N8n/thumbnail.png
  tips: {}
  title:
    custom: ""
    en_us: n8n
