name: big-bear-flcontainers-guacamole
services:
  app:
    cpu_shares: 90
    command: []
    container_name: big-bear-flcontainers-guacamole
    deploy:
      resources:
        limits:
          memory: 3919M
    environment:
      - EXTENSIONS=auth-totp,auth-ldap
      - tz=UTC
    hostname: big-bear-flcontainers-guacamole
    image: flcontainers/guacamole:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/guacamole.png
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
    restart: always
    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: User Timezone
        - container: EXTENSIONS
          description:
            en_us: Extensions to be enabled
      ports:
        - container: "8080"
          description:
            en_us: "Container Port: 8080"
    volumes: []
    devices: []
    cap_add: []
    networks:
      - default
    privileged: false
networks:
  default:
    name: big-bear-flcontainers-guacamole_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: A Docker Container for Apache Guacamole, a client-less remote desktop
      gateway. It supports standard protocols like VNC, RDP, and SSH over HTML5.
  developer: ""
  hostname: $host
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/guacamole.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: ""
  scheme: http
  store_app_id: big-bear-flcontainers-guacamole
  tagline:
    en_us: Fully packaged Multi-Arch Guacamole.
  thumbnail: ""
  title:
    custom: Guacamole
    en_us: FlContainers Guacamole
